## 03_답

In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV,StratifiedKFold
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
import seaborn as sns
import pandas as pd

In [4]:
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [6]:
titanic = pd.get_dummies(titanic, columns=["sex"], drop_first=True)

In [7]:
X = titanic.loc[:,"pclass":"fare"]
y = titanic["survived"]

print(X.shape)
print(y.shape)

X.info()
X.fillna(value=0, inplace=True)

(891, 5)
(891,)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   pclass  891 non-null    int64  
 1   age     714 non-null    float64
 2   sibsp   891 non-null    int64  
 3   parch   891 non-null    int64  
 4   fare    891 non-null    float64
dtypes: float64(2), int64(3)
memory usage: 34.9 KB


In [8]:
import numpy as np
dt = DecisionTreeClassifier()

params = {
    #"min_impurity_decrease":np.arange(0.001,0.01,0.0001),
    "max_depth":np.arange(3,20,1),
    "max_leaf_nodes":range(3,20,1)
    #"min_samples_split":np.arange(2,100,10)
}

splitter = StratifiedKFold(n_splits=5, shuffle= True)

gs_dt = GridSearchCV(dt, param_grid=params, cv = splitter)
gs_dt.fit(X,y)


GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=True),
             estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
                         'max_leaf_nodes': range(3, 20)})

In [10]:
print("Best parameters =", gs_dt.best_estimator_)
print("cv score = {:.4f}".format(gs_dt.best_score_))

Best parameters = DecisionTreeClassifier(max_depth=7, max_leaf_nodes=15)
cv score = 0.7116


In [19]:
## rf

rf = RandomForestClassifier()

params = {
    "n_estimators":range(90,120,1),     # 트리의 갯수 지정
    "max_depth":range(3,15,1)
}

splitter = StratifiedKFold(n_splits=5, shuffle= True)   #shuffle = T : bagging

grid_rf = GridSearchCV(rf, param_grid=params, cv = splitter)
grid_rf.fit(X,y)


GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=True),
             estimator=RandomForestClassifier(),
             param_grid={'max_depth': range(3, 15),
                         'n_estimators': range(90, 120)})

In [20]:
print("Best parameters =", grid_rf.best_estimator_)
print("cv score = {:.4f}".format(grid_rf.best_score_))

Best parameters = RandomForestClassifier(max_depth=6, n_estimators=109)
cv score = 0.7452


In [22]:
## gb

gb = GradientBoostingClassifier()

params = {
    "learning_rate": np.arange(0.1, 1, 0.1),  #range(0.1, 1, 0.1)이 오류발생이유
    "max_depth":range(3,20,1)                 #파이썬 함수는 int만 받음
}

splitter = StratifiedKFold(n_splits=5, shuffle=True)

grid_gb = GridSearchCV(gb, param_grid= params, cv = splitter)
grid_gb.fit(X,y)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=True),
             estimator=GradientBoostingClassifier(),
             param_grid={'learning_rate': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]),
                         'max_depth': range(3, 20)})

In [ ]:
print("Best parameters =", grid_gb.best_estimator_)
print("cv score = {:.4f}".format(grid_gb.best_score_))

## logistic

In [3]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [6]:
wine = pd.read_csv("http://bit.ly/wine-date")
wine

alcohol  sugar    pH  class
0         9.4    1.9  3.51    0.0
1         9.8    2.6  3.20    0.0
2         9.8    2.3  3.26    0.0
3         9.8    1.9  3.16    0.0
4         9.4    1.9  3.51    0.0
...       ...    ...   ...    ...
6492     11.2    1.6  3.27    1.0
6493      9.6    8.0  3.15    1.0
6494      9.4    1.2  2.99    1.0
6495     12.8    1.1  3.34    1.0
6496     11.8    0.8  3.26    1.0

[6497 rows x 4 columns]

In [8]:
wine["class"] = wine["class"].astype("int32").astype("category")
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype   
---  ------   --------------  -----   
 0   alcohol  6497 non-null   float64 
 1   sugar    6497 non-null   float64 
 2   pH       6497 non-null   float64 
 3   class    6497 non-null   float64 
 4   calss    6497 non-null   category
dtypes: category(1), float64(4)
memory usage: 209.6 KB


In [10]:
X = wine.iloc[:,:-1]
y = wine["class"]

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

##
standScaler = StandardScaler()
X_scaled = standScaler.fit_transform(X)
X_scaled[:10]

array([[-0.91546416, -0.7447781 ,  1.81308951, -1.75018984],
       [-0.58006813, -0.59764007, -0.11507303, -1.75018984],
       [-0.58006813, -0.66069923,  0.25811972, -1.75018984],
       [-0.58006813, -0.7447781 , -0.3638682 , -1.75018984],
       [-0.91546416, -0.7447781 ,  1.81308951, -1.75018984],
       [-0.91546416, -0.76579782,  1.81308951, -1.75018984],
       [-0.91546416, -0.80783726,  0.50691489, -1.75018984],
       [-0.41237012, -0.89191614,  1.06670401, -1.75018984],
       [-0.83161516, -0.72375839,  0.88010764, -1.75018984],
       [ 0.00687492,  0.13805008,  0.81790884, -1.75018984]])

In [33]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler  
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_validate, StratifiedGroupKFold, GridSearchCV

In [35]:
from sklearn.model_selection import cross_validate

lr = LogisticRegression(max_iter= 100)

splitter = StratifiedKFold(n_splits=5, shuffle= True)
scores = cross_validate(lr, X_scaled, y, cv = splitter)

In [36]:
print(scores["test_score"])

[1. 1. 1. 1. 1.]


In [28]:
lr.fit(X_scaled, y)

LogisticRegression()

In [31]:
print("probability = \n",lr.predict_proba(X_scaled[:10]))
print("\ncoefficient = \n", lr.coef_,lr.intercept_)
print("\nclasses = \n", lr.classes_)

probability = 
 [[9.99122053e-01 8.77946674e-04]
 [9.98307362e-01 1.69263771e-03]
 [9.98519064e-01 1.48093561e-03]
 [9.98303042e-01 1.69695755e-03]
 [9.99122053e-01 8.77946674e-04]
 [9.99130459e-01 8.69540505e-04]
 [9.98768944e-01 1.23105568e-03]
 [9.98912780e-01 1.08721975e-03]
 [9.98834164e-01 1.16583642e-03]
 [9.98017944e-01 1.98205567e-03]]

coefficient = 
 [[ 0.14218433  0.4581104  -0.28118984  5.82322614]] [4.13588247]

classes = 
 [0. 1.]


## 실습

In [66]:
Thoraric = pd.read_csv(r"C:\Users\user\Desktop\ml_part2_240912/ThoraricSurgery.csv", header = None) 
#header : 열이름 지정, False인 경우 1행 데이터가 컬럼으로 들어감

print(Thoraric.head())
Thoraric.shape


    0   1     2     3   4   5   6   7   8   9   10  11  12  13  14  15  16  17
0  293   1  3.80  2.80   0   0   0   0   0   0  12   0   0   0   1   0  62   0
1    1   2  2.88  2.16   1   0   0   0   1   1  14   0   0   0   1   0  60   0
2    8   2  3.19  2.50   1   0   0   0   1   0  11   0   0   1   1   0  66   1
3   14   2  3.98  3.06   2   0   0   0   1   1  14   0   0   0   1   0  80   1
4   17   2  2.21  1.88   0   0   1   0   0   0  12   0   0   0   1   0  56   0


(470, 18)

In [86]:
X = Thoraric.loc[:,1:16]
y = Thoraric[17]

train_X, test_X, train_y, test_y = train_test_split(
    X, y, test_size= 0.2
)

print(test_y)

144    0
130    0
343    0
164    1
12     0
      ..
207    0
296    0
275    0
160    0
453    0
Name: 17, Length: 94, dtype: int64


In [76]:
rf = RandomForestClassifier()

params = {
    "n_estimators":range(30,50,1),      #30 ~ 49까지의 트리 갯수
    "max_leaf_nodes":range(30,50,1)     #30 ~ 49까지의 마지막 노드 갯수
}

splitter = StratifiedKFold(n_splits= 5, shuffle= True)

grid_rf = GridSearchCV(rf, param_grid= params, cv = splitter)
grid_rf.fit(X,y)

c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\ma\core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=True),
             estimator=RandomForestClassifier(),
             param_grid={'max_leaf_nodes': range(30, 50),
                         'n_estimators': range(30, 50)})

In [77]:
print("Best parameters = ",grid_rf.best_estimator_)
print("cv score ={}".format(grid_rf.best_score_))

Best parameters =  RandomForestClassifier(max_leaf_nodes=32, n_estimators=36)
cv score =0.8553191489361703


In [92]:
import numpy as np

dt = DecisionTreeClassifier()

params = {
    "max_depth" : np.arange(3,20,1),
    "max_leaf_nodes" : range(3,20,1)
}
splitter = StratifiedGroupKFold(n_splits= 3, shuffle= True)

gs_dt = GridSearchCV(dt, param_grid= params, cv = splitter)
gs_dt.fit(X,y)

c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:982: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 971, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_scorer.py", line 455, in __call__
    return estimator.score(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 764, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
                             ^^^^^^^^^^^^^^^
  File 

GridSearchCV(cv=StratifiedGroupKFold(n_splits=3, random_state=None, shuffle=True),
             estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
                         'max_leaf_nodes': range(3, 20)})

In [80]:
print("Best parameters =", gs_dt.best_estimator_)
print("cv score = {:.4f}".format(gs_dt.best_score_))

Best parameters = DecisionTreeClassifier(max_depth=3, max_leaf_nodes=3)
cv score = nan
