#### Tensor란?
다차원의 배열을 뜻하는 말.<br>
배열의 차원에 따라 부르는 이름이 달라지는데요<br>
0차원은 스칼라(숫자하나), 1차원은 벡터(열), 2차원은 메트릭스, 그 이상의 다차원은 아래 차원의 것을 모아놓은 배열인 것이라 할 수 있는데요!<br>
tensor는 스칼라, 벡터, 매트릭스 등의 데이터와 그 이상의 고차원데이터도 포함하는 개념입니다.<br>참고로 tensor에서 Rank는 그 데이터가 몇 차원의 배열인지를 의미합니다

In [ ]:
import torch

numpy와 같은 다른 라이브러리도 tensor를 다룰 수 있는데 굳이 파이토치를 사용하는 이유는?<br>바로 파이토치에서는 gradient를 사용할 수 있기 때문입니다.

In [ ]:
x = torch.tensor(1., requires_grad = True) #trequires_grad = True : 미분계수를 계산할 수 있는 텐서 생성
w = torch.tensor(2., requires_grad = True)
b = torch.tensor(3., requires_grad = True)

# Bulid a computational graph, 계산 그래프를 작성합니다
y = w * x + b

print(y)

tensor(5., grad_fn=<AddBackward0>)


torch사용하기



In [ ]:
x = torch.tensor(1., requires_grad = True) #trequires_grad = True : 미분계수를 계산할 수 있는 텐서 생성
w = torch.tensor(2., requires_grad = True)
b = torch.tensor(3., requires_grad = True)

# Bulid a computational graph, 계산 그래프를 작성합니다
y = w * x + b

#gradient 계산 : backpropagation
y.backward()

#print out the gradients
print(x.grad) #tensor(2.) : x가 조금 변하면 결과값은 2배 변한다는 의미
print(w.grad)
print(b.grad)

tensor(5., grad_fn=<AddBackward0>)
tensor(2.)
tensor(1.)
tensor(1.)


```
Deep Learning 모델 학습 과정
1. 데이터 불러오기
2. Deep model만들기
3. loss, otimizer 만들기
4. 모델 통과 & loss 계산
5. 모델 개선
6. 학습된 모델 성능 평가하기
```
<br>
<br>
loss 함수(손실 함수) = 실제값과 예측값의 차이를 수치화 해주는 함수로<br> loss 함수를 최소화하는 weight와 bias를 찾도록 딥러닝 모델의 학습방향을 제시해주는 지표<br><br>optimizer = loss합수의 최솟값을 찾는 최적화 알고리즘,<br> loss함수를 최소화 하기 위해 parameters 업데이트를 위한 알고리즘!
<br>



In [ ]:
## numpy를 이용한 데이터셋 만들기
## torch는 numpy.array를 받을 수 없

import numpy as np

# step1. Create of shape
x = np.array([[1,2],[3,4]])
y = torch.from_numpy(x)

# Convert the numpy to a torch tensor. numpy 배열을 torch 텐서로 변환
y = torch.from_numpy(x)

# Convert the numpy to a torch numpy array. torch 텐서를 numpy array로 변환
z = y.numpy()

In [ ]:
import numpy as np

# step1. Create of shape
x = torch.randn(10,3)
y = torch.randn(10,2)

In [ ]:
#step2. Build a fully connected layer. deep model 만들기
import torch.nn as nn

linear = nn.Linear(3,2)
print("w:", linear.weight)
print("b:", linear.bias)

w: Parameter containing:
tensor([[-0.2541, -0.3975, -0.0535],
        [ 0.1993, -0.0624,  0.4918]], requires_grad=True)
b: Parameter containing:
tensor([0.4375, 0.3279], requires_grad=True)


In [ ]:
#step3. Build loss function and optimizer.
criterion = nn.MSELoss()  #nn.MSELoss : 제곱 평균 손실함수
optimizer = torch.optim.SGD(linear.parameters(), lr = 0.01) #lr : 보폭

In [ ]:
#step4. Forward pass. 모델 통과, loss 계산하기
pred = linear(x)

# compute loss. loss 계산
loss = criterion(pred, y)
print(loss)

tensor(1.9338, grad_fn=<MseLossBackward0>)


In [ ]:
# step5. Backward pass. 모델 계산하기
#gradient 초기화
loss.backward()

print("dL/dw:", linear.weight.grad)
print("dL/dw:", linear.bias.grad)

#1-step gradiend descent, gradient 변화적용
optimizer.step()

dL/dw: tensor([[-1.4917, -0.7240, -1.1677],
        [ 0.8445,  0.3729,  1.0493]])
dL/dw: tensor([0.3418, 1.9641])


In [ ]:
## step6. Print out the loss after 1-step gradient descent. 1-step gradient descent 이후에 loss를 출력
pred = linear(x)
loss = criterion(pred,y)
print("loss after 1-step optimization : ", loss.item())

loss after 1-step optimization :  1.8593733310699463


step5 ~ 6을 반복하게 된다면 loss값이 줄어드는 것을 확인할 수 있습니다!

###심화학습

cifar data load해보기

In [17]:
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms

train_dataset = torchvision.datasets.CIFAR10(root = '../../data/',
                                             train = True,
                                             transform = transforms.ToTensor(),
                                             download = True)



Files already downloaded and verified


In [3]:
# Fetch one data pair (read data from disk). 데이터 쌍 하나를 가져옵니다
image, label = train_dataset[0]
print(image.size())  #(r,g,b)
print(label)



torch.Size([3, 32, 32])
6


In [8]:
# Data loader (this provides queues and threads in a very simple way)
train_loader = torch.utils.data.DataLoader(dataset = train_dataset,
                                           batch_size = 64,
                                           shuffle = True)

# When iteration stats, queue and thread start to load data from files. 반복이 계속되면 queue와 thread는 파일에서 데이터를 불러오기 시작
data_iter = iter(train_loader)
print(data_iter)

# Mini - batch images and labels.
image, labels = next(data_iter)

print(labels)
# Actual usage of the data loader is as below.
for images, labels in train_loader:
  #Training code should be written here.
  pass


tensor([4, 3, 4, 4, 2, 4, 5, 2, 6, 1, 6, 2, 8, 4, 5, 5, 5, 9, 3, 6, 2, 9, 5, 9,
        3, 1, 7, 7, 8, 7, 1, 7, 6, 3, 3, 4, 9, 6, 5, 3, 5, 0, 7, 6, 1, 8, 4, 4,
        6, 5, 3, 0, 6, 1, 4, 2, 5, 4, 3, 7, 7, 5, 2, 1])


In [13]:
# for i in range(10):
#   print(i)

#a = iter(range(10))
next(a)


3

custom dataset 제작

In [ ]:
class CustomDataset(torch.utils.data.Dataset):
  def __init__(self):
    pass
  def __getitem(self, index):
    pass
    def __len__(self):
      return 0

custom_dataset = CustomDataset()
train_loader = torch.utils.data.DataLoader(dataset = custom_dataset,
                                           batch_size = 64,
                                           shuffle = True)

사전학습된 모델 가져오기

In [18]:
resnet = torchvision.models.resnet18(pretrained = True)

# if u want to finetune only the top layer of the model, set as below
# top layer(가장 최근의 layer)만을 미세조정하고 싶다면, 아래와 같이 설정
for param in resnet.parameters():
  param.requires_grad = False

resnet.fc = nn.Linear(resnet.fc.in_features, 100)

# Forward pass. 전방 전달
images = torch.randn(64, 3, 224, 224)
outputs = resnet(images)
print(outputs.size())



torch.Size([64, 100])


모델 저장하기

In [19]:
#전체 모델 저장
torch.save(resnet, "model.ckpt")
model = torch.load("model.ckpt")

# 모델의 파라미터만 저장후 불러옴(추천)
torch.save(resnet.state_dict(), "params.ckpt")
resnet.load_state_dict(torch.load("params.ckpt"))

<ipython-input-19-c031c74c2fed>:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load("model.ckpt")
<ipython-input-19-c031c74c2fed>:5: FutureWarning: You are u

<All keys matched successfully>